[2025-07-30T00:21:26.183+0000] {processor.py:161} INFO - Started process (PID=34241) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:21:26.184+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:21:26.186+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:21:26.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:21:26.191+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:21:26.190+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:21:26.191+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:21:26.191+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:21:26.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:21:26.205+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-30T00:22:18.743+0000] {processor.py:161} INFO - Started process (PID=34326) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:22:18.744+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:22:18.745+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:22:18.745+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:22:18.750+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:22:18.749+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:22:18.750+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:22:18.750+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:22:18.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:22:18.764+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-30T00:23:09.655+0000] {processor.py:161} INFO - Started process (PID=34396) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:23:09.657+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:23:09.658+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:23:09.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:23:09.663+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:23:09.662+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:23:09.664+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:23:09.663+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:23:09.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:23:09.679+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-30T00:24:10.244+0000] {processor.py:161} INFO - Started process (PID=34487) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:24:10.246+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:24:10.247+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:24:10.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:24:10.251+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:24:10.250+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:24:10.252+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:24:10.251+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:24:10.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:24:10.268+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-30T00:25:01.201+0000] {processor.py:161} INFO - Started process (PID=34559) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:25:01.202+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:25:01.204+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:25:01.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:25:01.210+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:25:01.208+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:25:01.210+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:25:01.210+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:25:01.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:25:01.229+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-07-30T00:26:01.450+0000] {processor.py:161} INFO - Started process (PID=34651) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:26:01.454+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T00:26:01.455+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:26:01.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:26:01.465+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:26:01.463+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T00:26:01.465+0000] {logging_mixin.py:188} INFO - [2025-07-30T00:26:01.465+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T00:26:01.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T00:26:01.505+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-07-30T20:46:02.079+0000] {processor.py:161} INFO - Started process (PID=1358) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:02.080+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T20:46:02.081+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:02.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:02.085+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:02.084+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T20:46:02.085+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:02.085+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T20:46:02.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:02.101+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-30T20:46:50.873+0000] {processor.py:161} INFO - Started process (PID=1413) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:50.874+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T20:46:50.875+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:50.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:50.879+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:50.878+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T20:46:50.879+0000] {logging_mixin.py:188} INFO - [2025-07-30T20:46:50.879+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T20:46:50.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T20:46:50.891+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-30T21:03:09.076+0000] {processor.py:161} INFO - Started process (PID=1636) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:03:09.077+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T21:03:09.078+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:03:09.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:03:09.083+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:03:09.082+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T21:03:09.083+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:03:09.083+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T21:03:09.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:03:09.095+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-30T21:04:10.433+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:04:10.434+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T21:04:10.437+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:04:10.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:04:10.444+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:04:10.443+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T21:04:10.444+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:04:10.444+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T21:04:10.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:04:10.456+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-30T21:05:02.597+0000] {processor.py:161} INFO - Started process (PID=1748) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:02.599+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T21:05:02.600+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:02.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:02.607+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:02.606+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T21:05:02.608+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:02.608+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T21:05:02.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:02.620+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-30T21:05:57.266+0000] {processor.py:161} INFO - Started process (PID=1804) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:57.267+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T21:05:57.268+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:57.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:57.272+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:57.271+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T21:05:57.273+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:05:57.272+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T21:05:57.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:05:57.285+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-30T21:06:51.598+0000] {processor.py:161} INFO - Started process (PID=1858) to work on /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:06:51.601+0000] {processor.py:830} INFO - Processing file /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-30T21:06:51.602+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:06:51.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:06:51.606+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:06:51.605+0000] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-30T21:06:51.606+0000] {logging_mixin.py:188} INFO - [2025-07-30T21:06:51.606+0000] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-30T21:06:51.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-30T21:06:51.619+0000] {processor.py:183} INFO - Processing /home/azureuser/.pyenv/versions/3.11.9/envs/airflow-venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
